ArcadeBar/ArcadeBar/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('base.urls')),
    path('admin/',admin.site.urls),
    path('', include("django.contrib.auth.urls")),
]

ArcadeBar/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.user_login, name="login"),
    path('signup/', views.user_signup, name="signup"),
    path('logout/', views.user_logout, name="logout"),
]

ArcadeBar/base/urls.py
from django.urls import path, include
from django.contrib import admin
from . import views



urlpatterns = [
    path('', views.home, name = "home"),
    path('contact/', views.contact, name="contact"),
    path('bowling/', views.bowling, name="bowling"),
    path('billiards/', views.billiards, name="billiards"),
    path('darts/', views.darts, name="darts"),
    path('bowling/price/', views.bowlingPrice, name="bowlingPrice"),
    path('billiards/price/', views.billiardsPrice, name="billiardsPrice"),
    path('darts/price/', views.dartsPrice, name="dartsPrice"),
    path('accounts/', include('accounts.urls')),
    path('booking/', views.booking, name='booking'),
    path('booking-submit/', views.bookingSubmit, name='bookingSubmit'),
    path('user-panel', views.userPanel, name='userPanel'),
    path('user-update/<int:id>', views.userUpdate, name='userUpdate'),
    path('user-update-submit/<int:id>', views.userUpdateSubmit, name='userUpdateSubmit'),
    path('staff-panel/', views.staffPanel, name='staffPanel'),
    path('staffDelete/<int:id>', views.staffDelete, name='staffDelete'),
    path('userCancel/<int:id>', views.userCancel, name='userCancel'),
    path('merchshop/', include('merchshop.urls')),
]

ArcadeBar/merchshop/urls.py
from django.urls import path
from . import views

app_name = 'merchshop'
urlpatterns = [
    path('', views.merch, name='merch'),
    path('cart/<int:id>', views.cart, name="cart"),
    path('checkout/<int:id>', views.checkout, name="checkout"),
    path('thankYou/<int:id>', views.thankYou, name="thankYou"),
]

ArcadeBar/base/models.py
from tkinter import CASCADE
from django.db import models
from datetime import datetime
from django import forms 
from accounts.models import CustomUser
# Create your models here.
SERVICE_CHOICES = (
    ("Bowling", "Bowling"),
    ("Darts", "Darts"),
    ("Billiards", "Billiards"),
    )
TIME_CHOICES = (
    ("3 PM", "3 PM"),
    ("3:30 PM", "3:30 PM"),
    ("4 PM", "4 PM"),
    ("4:30 PM", "4:30 PM"),
    ("5 PM", "5 PM"),
    ("5:30 PM", "5:30 PM"),
    ("6 PM", "6 PM"),
    ("6:30 PM", "6:30 PM"),
    ("7 PM", "7 PM"),
    ("7:30 PM", "7:30 PM"),
)

class Appointment(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True, blank=True)
    service = models.CharField(max_length=50, choices=SERVICE_CHOICES, default="Bowling")
    day = models.DateField(default=datetime.now)
    time = models.CharField(max_length=10, choices=TIME_CHOICES, default="3 PM")
    time_ordered = models.DateTimeField(default=datetime.now, blank=True)
    def __str__(self):
        return f"{self.user.username} | day: {self.day} | time: {self.time}"

ArcadeBar/base/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.urls import reverse
from django.views.decorators.http import require_POST
from django.core.mail import send_mail
from .models import *
from django.contrib import messages
from datetime import datetime, timedelta


# Create your views here.
def home(request):
    context = []
    return render(request, 'base/home.html')

def contact(request):
    context= []
    return render(request, 'base/contact.html')

def bowling(request):
    return render(request, 'base/bowling.html')

def billiards(request):
    return render(request, 'base/billiards.html')

def darts(request):
    return render(request, 'base/darts.html')

def bowlingPrice(request):
    return render(request, 'base/bowlingPrice.html')

def billiardsPrice(request):
    return render(request, 'base/billiardsPrice.html')

def dartsPrice(request):
    return render(request, 'base/dartsPrice.html')


def contact(request):
    if(request.method == 'POST'):
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')

        recipient = 'arcadeBarhr@gmail.com'  

        send_mail(
            f'New message from {name}',
            f'From: {email}\n\n{message}',
            email,
            [recipient],
            fail_silently=False,
        )

        messages.success(request, 'Your message has been sent successfully!')
        return redirect('home')
    else:
        return render(request, 'base/contact.html')


def booking(request):
    #Calling 'validWeekday' Function to Loop days you want in the next 21 days:
    weekdays = validWeekday(22)

    #Only show the days that are not full:
    validateWeekdays = isWeekdayValid(weekdays)
    

    if request.method == 'POST':
        service = request.POST.get('service')
        day = request.POST.get('day')
        description = request.POST.get('description')
        if service == None:
            messages.success(request, "Please Select A Service!")
            return redirect('booking')

        #Store day and service in django session:
        request.session['day'] = day
        request.session['service'] = service
        request.session['description'] = description

        return redirect('bookingSubmit')

    return render(request, 'base/booking.html', {
        'weekdays':weekdays,
        'validateWeekdays':validateWeekdays,
    })


def bookingSubmit(request):
    user = request.user
    times = [
        "3 PM", "4 PM", "5 PM", "6 PM", "7 PM", "8 PM", "9 PM", "10 PM"
    ]
    today = datetime.now()
    minDate = today.strftime('%Y-%m-%d')
    deltatime = today + timedelta(days=21)
    strdeltatime = deltatime.strftime('%Y-%m-%d')
    maxDate = strdeltatime

    #Get stored data from django session:
    day = request.session.get('day')
    service = request.session.get('service')
    #Only show the time of the day that has not been selected before:
    hour = checkTime(times, day)
    if request.method == 'POST':
        time = request.POST.get("time")
        date = dayToWeekday(day)

        if service != None:
            if day <= maxDate and day >= minDate:
                if date == 'Sunday' or date == 'Saturday' or date == 'Wednesday' or date == 'Thursday' or date == 'Friday' or date == 'Tuesday': 
                    if Appointment.objects.filter(day=day).count() < 11:
                        if Appointment.objects.filter(day=day, time=time).count() < 1:
                            AppointmentForm = Appointment.objects.get_or_create(
                                user = user,
                                service = service,
                                day = day,
                                time = time,
                                
                            )
                            messages.success(request, "Appointment Saved!")
                            return redirect('userPanel')
                        else:
                            messages.success(request, "The Selected Time Has Been Reserved Before!")
                    else:
                        messages.success(request, "The Selected Day Is Full!")
                else:
                    messages.success(request, "The Selected Date Is Incorrect")
            else:
                    messages.success(request, "The Selected Date Isn't In The Correct Time Period!")
        else:
            messages.success(request, "Please Select A Service!")


    return render(request, 'base/bookingSubmit.html', {
        'times':hour,
    })

def userPanel(request):
    user = request.user
    appointments = Appointment.objects.filter(user=user).order_by('day', 'time')
    return render(request, 'base/userPanel.html', {
        'user':user,
        'appointments':appointments,
    })

def userUpdate(request, id):
    appointment = Appointment.objects.get(pk=id)
    userdatepicked = appointment.day
    #Copy  booking:
    today = datetime.today()
    minDate = today.strftime('%Y-%m-%d')

    #24h if statement in template:
    delta24 = (userdatepicked).strftime('%Y-%m-%d') >= (today + timedelta(days=1)).strftime('%Y-%m-%d')
    #Calling 'validWeekday' Function to Loop days you want in the next 21 days:
    weekdays = validWeekday(22)

    #Only show the days that are not full:
    validateWeekdays = isWeekdayValid(weekdays)
    

    if request.method == 'POST':
        service = request.POST.get('service')
        day = request.POST.get('day')

        #Store day and service in django session:
        request.session['day'] = day
        request.session['service'] = service

        return redirect('userUpdateSubmit', id=id)


    return render(request, 'base/userUpdate.html', {
            'weekdays':weekdays,
            'validateWeekdays':validateWeekdays,
            'delta24': delta24,
            'id': id,
        })

def userUpdateSubmit(request, id):
    user = request.user
    times = [
        "3 PM", "4 PM", "5 PM", "6 PM", "7 PM", "8 PM", "9 PM", "10 PM"
    ]
    today = datetime.now()
    minDate = today.strftime('%Y-%m-%d')
    deltatime = today + timedelta(days=21)
    strdeltatime = deltatime.strftime('%Y-%m-%d')
    maxDate = strdeltatime

    day = request.session.get('day')
    service = request.session.get('service')
    
    #Only show the time of the day that has not been selected before and the time he is editing:
    hour = checkEditTime(times, day, id)
    appointment = Appointment.objects.get(pk=id)
    userSelectedTime = appointment.time
    if request.method == 'POST':
        time = request.POST.get("time")
        date = dayToWeekday(day)

        if service != None:
            if day <= maxDate and day >= minDate:
                if date == 'Sunday' or date == 'Tuesday' or date == 'Thursday' or date == 'Wednesday' or date == 'Friday' or date == 'Saturday':
                    if Appointment.objects.filter(day=day).count() < 11:
                        if Appointment.objects.filter(day=day, time=time).count() < 1 or userSelectedTime == time:
                            AppointmentForm = Appointment.objects.filter(pk=id).update(
                                user = user,
                                service = service,
                                day = day,
                                time = time
                            ) 
                            messages.success(request, "Appointment Edited!")
                            return redirect('userPanel')
                        else:
                            messages.success(request, "The Selected Time Has Been Reserved Before!")
                    else:
                        messages.success(request, "The Selected Day Is Full!")
                else:
                    messages.success(request, "The Selected Date Is Incorrect")
            else:
                    messages.success(request, "The Selected Date Isn't In The Correct Time Period!")
        else:
            messages.success(request, "Please Select A Service!")
        return redirect('userPanel')


    return render(request, 'base/userUpdateSubmit.html', {
        'times':hour,
        'id': id,
    })


def dayToWeekday(x):
    z = datetime.strptime(x, "%Y-%m-%d")
    y = z.strftime('%A')
    return y

def validWeekday(days):
    #Loop days you want in the next 21 days:
    today = datetime.now()
    weekdays = []
    for i in range (0, days):
        x = today + timedelta(days=i)
        y = x.strftime('%A')
        if y == 'Sunday' or y == 'Tuesday' or y == 'Wednesday' or y == 'Thursday' or y == 'Friday' or y == 'Saturday':
            weekdays.append(x.strftime('%Y-%m-%d'))
    return weekdays
    
def isWeekdayValid(x):
    validateWeekdays = []
    for j in x:
        if Appointment.objects.filter(day=j).count() < 10:
            validateWeekdays.append(j)
    return validateWeekdays

def checkTime(times, day):
    #Only show the time of the day that has not been selected before:
    x = []
    for k in times:
        if Appointment.objects.filter(day=day, time=k).count() < 1:
            x.append(k)
    return x

def checkEditTime(times, day, id):
    #Only show the time of the day that has not been selected before:
    x = []
    appointment = Appointment.objects.get(pk=id)
    time = appointment.time
    for k in times:
        if Appointment.objects.filter(day=day, time=k).count() < 1 or time == k:
            x.append(k)
    return x



def staffPanel(request):
    appointments = Appointment.objects.all()
    context = {
        'appointments' : appointments
    }
    return render(request, 'base/staffPanel.html', context)


def staffDelete(request, id):
    appointment = Appointment.objects.get(pk=id)
    appointment.delete()
    messages.success(request, "Appointment successfully deleted by staff: " + request.user.username + "!")
    return redirect('staffPanel')

def userCancel(request, id):
    appointment = Appointment.objects.get(pk=id)

ArcadeBar/base/templates/base/base.html
    <header>
        <div class="container">
            <img src="../../static/images/bowling.png" alt="ArcadeBar Logo" class="logo">
          <nav>
            <ul> 
              <li><a href="{% url 'home' %}">Home</a></li>
              <li><a href="{% url 'merchshop:merch' %}">Merch!</a></li>
              <li><a href="{% url 'booking' %}">Reservation</a></li>  
              <li><a href="{% url 'contact' %}">Contact</a></li>    
            </ul>
          </nav>
    
          <nav>
            <ul>
                {% if request.user.is_authenticated %}
                <li>Logged in: {{request.user.username}}</li>
                {% if request.user.is_staff %}
                <li><a href="{% url 'staffPanel' %}">Update reservations</a></li>
                {% endif %}
                <li><a href="{% url 'userPanel' %}">Profile</a></li>
                <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'accounts:login' %}">Log in</a></li>
                <li><a href="{% url 'accounts:signup' %}">Sign up</a></li> 
                {% endif %}
            </ul>
          </nav>

        </div>
        
      </header>
      <div>
        {% if request.user.is_superuser %}
        <a href= "/admin">Admin</a>
        {% endif %}
      </div>
      {% block content%}
      {% endblock content %}



  

ArcadeBar/base/templates/base/billiards.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="../../static/base/arcade.css">
</head>
<body>
    {% extends 'base/base.html' %}

    {% block content %}

    <div class="uvod">
        <img src="../../static/images/enlarge_image.jpg" alt="biljar">
        <div class="uvod-text">Billiards</div>
        <div class="uvod-buttons">
            <div class="pricing-link">
                <a href="{% url 'billiardsPrice' %}">Pricing</a>
            </div>
            <div class="reserve-link">
                {% if request.user.is_authenticated %}
                <a href="{% url 'reservation' %}">Reserve</a>
                {% else %}
                <a href="{% url 'accounts:login' %}">Reserve</a>
                {% endif %}
            </div>
        </div>
    </div>
           
    <div class="left-wrapper">
        <div class="left">
            <div class="left-text-wrapper">
                <h2>Origins</h2>
                <div class="left-text">
                    <p>
                        Billiards, a cue sport played on a rectangular table covered with a cloth and bounded by cushions, has a history dating back centuries. Its precise origins are somewhat unclear, but it is believed to have originated in Europe during the 15th century. Initially, it was an outdoor lawn game similar to croquet but eventually moved indoors and evolved into the indoor cue sport we recognize today.                            
                    </p>
                </div>
            </div>
        </div>
        <img src="../../static/images/c8e368a8e69103e4eabef70c75e0d19b1932fee3_1700-s-1.webp" alt="billiards1">
    </div>

            <div class="right-wrapper">
                <img src="../../static/images/billiards uvod 2.webp" alt="billiards2">
                <div class="right">
                    <div class="right-text-wrapper">
                        <h2>Rules</h2>
                        <div class="right-text">
                            <p>
                                The rules of billiards vary depending on the specific game being played. For example, in eight-ball, players are assigned either the solid or striped balls, and they must pocket all their designated balls before attempting to sink the eight-ball to win. Nine-ball involves players pocketing balls in numerical order, with the player pocketing the nine-ball winning the game.                        
                            </p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="left-wrapper">
                <div class="left">
                    <div class="left-text-wrapper">
                        <h2>Billiard balls and stick</h2>
                        <div class="left-text">
                            <p>
                                Billiard balls are typically made of phenolic resin or other durable materials. In a standard set, there are 16 balls, including one white cue ball and a set of numbered object balls. The cue stick, used by players to strike the cue ball, is usually made of wood. It consists of a shaft and a tip, with the tip often covered in leather.                            
                            </p>
                        </div>
                    </div>
                </div>
                <img src="../../static/images/Billiards-Snooker-Series-Modern-Sports-Vintage-Canvas-Painting-Poster-Aesthetic-Wall-Pictures-Bedroom-bar-cafe-club.jpg_640x640.webp" alt="billiards3">
            </div>

            <div class="right-wrapper">
                <img src="../../static/images/billiard-games.jpeg" alt="billiards4">
                <div class="right">
                    <div class="right-text-wrapper">
                        <h2>Required skills</h2>
                        <div class="right-text">
                            <p>
                                Playing billiards demands precise cue ball control, accuracy in shot placement, and strategic thinking for shot selection. A skilled player exhibits a consistent stroke, adaptability to different table conditions, and emotional control during competitive play. Developing these skills through practice and experience is essential for success in the game of billiards.                            
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            
    <div class="blank-space"></div>

      <footer>
        <p>&copy; 2024 Arcade Bar</p>
        <p><a href="#">Privacy Policy</a> | <a href="#">Terms of Service</a></p>
      </footer>
      {% endblock content %}
</body>
</html>

ArcadeBar/base/templates/base/booking.html
<link rel="stylesheet" href="../../static/base/home.css">
<link rel="stylesheet" href="../../static/base/booking.css">
{% extends 'base/base.html' %}
{% block content %}

<div class="container1">
{% if user.is_authenticated %}
<h1>Online Booking</h1>

<div class="shadow p-4 mb-5 bg-body bg-body rounded text-black  m-5 ">
    <form method="post" action="{% url 'booking' %}" class="me-2 ms-2" required>
        {% csrf_token %}

        <!--input service-->
        <div class="form-group">
            <h3 class="form-label">Select activity:</h3>
            <select class="form-select fs-3" name="service">
                <option value="Bowling">Bowling</option>
                <option value="Darts">Darts</option>
                <option value="Billiards">Billiards</option>
            </select>
        </div>
            <!--input day-->
            <div class="form-group fs-3">
                <h3 class="form-label">Select Day:</h3>
                <select class="form-select fs-3" name="day">
                    {% for validateWeekday in validateWeekdays %}
                    <option value="{{validateWeekday}}">{{validateWeekday}}</option>
                    {% endfor %}
                </select>
            </div>

            <br/>
            <button type="submit" class="btn btn-primary">Continue</button>
        </div>
    </form>
</div>

{% else %}

<div class="panel shadow p-4 mb-5 bg-body bg-body rounded text-black  m-5 ">
    <h1 class="p-2  me-3">You Are Not Signed in!</h1>
    <a href="{% url 'accounts:login' %}" class="btn btn-primary shadow text-center">Sign in</a>
</div>

{% endif %}
</div>

{% endblock %}

ArcadeBar/base/templates/base/bookingSubmit.html
<link rel="stylesheet" href="../../static/base/home.css">
<link rel="stylesheet" href="../../static/base/userUpdateSubmit.css">
{% extends 'base/base.html' %}

<title>Online Booking</title>
<div class="container1">
{% block content %}


{% if user.is_authenticated %}
<h1 class="text-center fPersian mt-3">Online Booking</h1>

<div class="panel shadow p-4 mb-5 bg-body bg-body rounded text-black text-center m-5">
    <form method="post" action="{% url 'bookingSubmit' %}" class="me-2 ms-2" required>
        {% csrf_token %}
        
        <!--input time-->
        <h3 class="form-label fPersian mt-4">Time:</h3>
        <div>
            <select class="form-select fs-3 text-center" name="time">
                {% for time in times %}
                <option value="{{time}}">{{time}}</option>
                {% endfor %}
            </select>
        </div>

        <button type="submit" class="btn btn-primary text-white mt-3 fPersian">Submit</button>

    </form>
</div>

{% else %}

<div class="panel shadow p-4 mb-5 bg-body bg-body rounded text-black  m-5">
    <h1 class="p-2  me-3">First Sign in!</h1>
    <a href="{% url 'accounts:login' %}" class="btn btn-primary text-white">Sign in</a>
</div>

{% endif %}


{% endblock content %}
</div>

ArcadeBar/base/templates/base/bowling.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="../../static/base/arcade.css">
</head>
<body>
    {% extends 'base/base.html' %}

    {% block content %}


    <div class="uvod" id="bowling-uvod">
        <img src="../../static/images/rapids6-1500x630.jpg" alt="kuglana">
        <div class="uvod-text">Bowling</div>
        <div class="uvod-buttons">
            <div class="pricing-link">
                <a href="{% url 'bowlingPrice' %}">Pricing</a>
            </div>
            <div class="reserve-link">
                {% if request.user.is_authenticated %}
                <a href="{% url 'booking' %}">Reserve</a>
                {% else %}
                <a href="{% url 'accounts:login' %}">Reserve</a>
                {% endif %}
            </div>
        </div>
    </div>
      
            <div class="left-wrapper">
                <div class="left">
                    <div class="left-text-wrapper">
                        <h2>Origins</h2>
                        <div class="left-text">
                            <p>
                                Bowling, one of the world's oldest sports, has a rich history dating back over 5,000 years. Its origins can be traced to ancient Egypt, where artifacts resembling bowling balls and pins were discovered. The game evolved over centuries and spread across various cultures, with the British, Dutch, and Germans each contributing to its development. In the 19th century, the standardization of rules occurred, leading to the modern form of the game.
                            </p>
                        </div>
                    </div>
                </div>
                <img src="../../static/images/LSyMWcE6-Bowling-1200x800.jpg" alt="bowling1">
            </div>

            <div class="right-wrapper">
                <img src="../../static/images/bowling-banner_2.jpg" alt="bowling2">
                <div class="right">
                    <div class="right-text-wrapper">
                        <h2>Rules</h2>
                        <div class="right-text">
                            <p>
                                In a standard game of bowling, each player has ten frames to roll their ball down the lane. In each frame, the player has two attempts to knock down all ten pins. If all pins are knocked down with the first ball (a strike), it counts as 10 pins plus the pinfall from the next two rolls. If the player knocks down all the pins with the second ball (a spare), it counts as 10 pins plus the pinfall from the next roll. The game's objective is to accumulate the highest total score across all frames.                    </p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="left-wrapper">
                <div class="left">
                    <div class="left-text-wrapper">
                        <h2>Bowling balls</h2>
                        <div class="left-text">
                            <p>
                                Bowling balls are typically made of urethane, reactive resin, or plastic. They come in various weights, ranging from 6 to 16 pounds (2.72 to 7.25 kilograms). The weight of the ball is a personal preference, with many bowlers selecting a weight that allows for control and accuracy. The choice of the ball's surface, as well as its internal core design, can influence its performance on the lane                    
                            </p>
                        </div>
                    </div>
                </div>
                <img src="../../static/images/Runway 2024-01-14T11_09_04.112Z Expand Image.jpg" alt="bowling3">
            </div>

            <div class="right-wrapper">
                <img src="../../static/images/bowlingshoes-1500x630.jpg" alt="bowling4">
                <div class="right">
                    <div class="right-text-wrapper">
                        <h2>Bowling shoes</h2>
                        <div class="right-text">
                            <p>
                                Specialized bowling shoes are a crucial part of the game. They feature a sliding sole on one foot and a braking sole on the other. This design allows bowlers to slide on the approach (the area before the lane) with one foot while maintaining stability with the other. The sliding sole helps achieve a smooth delivery, while the braking sole ensures control and balance. Using regular shoes on the lane can damage the surface and compromise a bowler's performance.                </div>
                    </div>
                </div>
            </div>

    <div class="blank-space"></div>

      <footer>
        <p>&copy; 2024 Arcade Bar</p>
        <p><a href="#">Privacy Policy</a> | <a href="#">Terms of Service</a></p>
      </footer>
      {% endblock content %}
</body>
</html>

ArcadeBar/base/templates/base/userPanel.html
<link rel="stylesheet" href="../../static/base/home.css">
<link rel="stylesheet" href="../../static/base/userPanel.css">
{% extends 'base/base.html' %}


<div class="container1">
{% block content %}

{% if user.is_authenticated %}
<h1 class="user-panel">User Panel</h1>

<div class="user-info">
    <h2>User Info</h2>
    <ul>
            <li><strong>First Name:</strong> {{ user.first_name }}</li>
            <li><strong>Last Name:</strong> {{ user.last_name }}</li>
            <li><strong>Username:</strong> {{ user.username }}</li>
    </ul>
</div>


{% if messages %}
<div class="alerts">
        {% for message in messages %}
            <div class="alert alert-success">
                <h3>{{ message }}</h3>
                <!-- <button type="button" class="btn-close">Close</button> -->
            </div>
        {% endfor %}
    </div>
{% endif %}

<!--Appointment Loop-->
{% if appointments.count > 0 %}
<div class="reservations">
    <h1>Reservations</h1>
    <br>
    <div class="reservation">
        {% for appointment in appointments %}
        <div class="reservation1 list-group fs-4 border p-3 mb-3">
            <p class="list-group mt-2"><strong>Day:</strong> {{ appointment.day }}</p>
            <p class="list-group mt-2"><strong>Termin: </strong> {{ appointment.time }}</p>
            <p class="list-group mt-2"><strong>Activity:</strong> {{ appointment.service }}</p>
            <p class="list-group mt-2"> <strong>Ordered at:</strong> {{ appointment.time_ordered }}</p>
            
            <div class="mt-3 mb-2">
                <a class="edit-btn" href="{% url 'userUpdate' appointment.id %}">Edit Appointment</a>
            </div>
                <a class="cancel-btn" href="{% url 'userCancel' appointment.id %}">Cancel</a>
            {% if user.is_superuser %}
                
            {% endif %}
            <br>
            
        </div>
        {% endfor %}
    </div>
</div>
{% endif %}

{% else %}

<div class="first-sign-in">
    <h1 class="p-2  ms-3">First Sign in!</h1>
    <a href="{% url 'accounts:login' %}" class="btn btn-primary">Sign in</a>
</div>

{% endif %}


{% endblock content %}
</div>

ArcadeBar/base/templates/base/userUpdate.html
<link rel="stylesheet" href="../../static/base/home.css">
<link rel="stylesheet" href="../../static/base/userUpdate.css">
{% extends 'base/base.html' %}



{% block content %}

<div class="container1">
{% if user.is_authenticated %}
<!--if 24hrs before nobat-->
{% if delta24 == True %}
<h1 class="text-center  mt-3">Edit Appointment</h1>

<div class="shadow p-4 mb-5 bg-body bg-body rounded text-black  m-5 ">
    <form method="post" action="{% url 'userUpdate' id %}" class="me-2 ms-2" required>
        {% csrf_token %}

        <!--input service-->
        <div>
            <h3 class="">Select activity:</h3>
            <select class="form-select input-text" name="service">
                <option value="Bowling">Bowling</option>
                <option value="Darts">Darts</option>
                <option value="Billiards">Billiards</option>
            </select>
        </div>
            <!--input day-->
            <div class="mt-3">
                <h3 class="">Select Day:</h3>
                <select class="form-select input-text" name="day">
                    {% for validateWeekday in validateWeekdays %}
                    <option value="{{validateWeekday}}">{{validateWeekday}}</option>
                    {% endfor %}
                </select>
            </div>

            <br/>
            <button type="submit" class="btn btn-primary">Continue</button>
        </div>
    </form>
</div>
<!--else if its 24hrs before editing-->
{% else %}

<div class="shadow p-4 mb-5 bg-body bg-body rounded text-black m-5">
    <h1 class="text-danger">Editing Appointments Its Only Available 24hrs Before Appointment!</h1>
    <a href="{% url 'userPanel' %}" class="btn btn-primary shadow text-center">Return To User Panel</a>
</div>

{% endif %}


{% else %}

<div class="shadow p-4 mb-5 bg-body bg-body rounded text-black  m-5 ">
    <h1 class="p-2  me-3">You Are Not Signed in!</h1>
    <a href="{% url 'accounts:login' %}" class="btn btn-primary shadow text-center">Sign in</a>
</div>
</div>
{% endif %}


{% endblock content %}