ArcadeBar/ArcadeBar/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('base.urls')),
    path('admin/',admin.site.urls),
    path('', include("django.contrib.auth.urls")),
]

ArcadeBar/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.user_login, name="login"),
    path('signup/', views.user_signup, name="signup"),
    path('logout/', views.user_logout, name="logout"),
]

ArcadeBar/base/urls.py
from django.urls import path, include
from django.contrib import admin
from . import views



urlpatterns = [
    path('', views.home, name = "home"),
    path('contact/', views.contact, name="contact"),
    path('bowling/', views.bowling, name="bowling"),
    path('billiards/', views.billiards, name="billiards"),
    path('darts/', views.darts, name="darts"),
    path('bowling/price/', views.bowlingPrice, name="bowlingPrice"),
    path('billiards/price/', views.billiardsPrice, name="billiardsPrice"),
    path('darts/price/', views.dartsPrice, name="dartsPrice"),
    path('accounts/', include('accounts.urls')),
    path('booking/', views.booking, name='booking'),
    path('booking-submit/', views.bookingSubmit, name='bookingSubmit'),
    path('user-panel', views.userPanel, name='userPanel'),
    path('user-update/<int:id>', views.userUpdate, name='userUpdate'),
    path('user-update-submit/<int:id>', views.userUpdateSubmit, name='userUpdateSubmit'),
    path('staff-panel/', views.staffPanel, name='staffPanel'),
    path('staffDelete/<int:id>', views.staffDelete, name='staffDelete'),
    path('userCancel/<int:id>', views.userCancel, name='userCancel'),
    path('merchshop/', include('merchshop.urls')),
]

ArcadeBar/merchshop/urls.py
from django.urls import path
from . import views

app_name = 'merchshop'
urlpatterns = [
    path('', views.merch, name='merch'),
    path('cart/<int:id>', views.cart, name="cart"),
    path('checkout/<int:id>', views.checkout, name="checkout"),
    path('thankYou/<int:id>', views.thankYou, name="thankYou"),
]

ArcadeBar/merchshop/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    image = models.URLField()
    description = models.TextField()


    def __str__ (self):
        return self.title + " - " + str(self.price)

class Order(models.Model):
    article = models.OneToOneField(Article, on_delete=models.CASCADE)
    amount = models.IntegerField()

ArcadeBar/merchshop/views.py
from pyexpat.errors import messages
import re
from django.shortcuts import render
from . models import Article, Order
from accounts.models import CustomUser
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
# Create your views here.


def merch(request):
    articles = Article.objects.all()
    context = {'articles': articles}
    return render(request, 'merchshop/merch.html', context)



def cart(request, id):
    if request.method == 'POST':
        article = Article.objects.get(id=id)
        context = {'article': article}
        return render(request, 'merchshop/cart.html', context)
    else:
        return render(request, 'merchshop/cart.html')
    
def checkout(request, id):
    if request.method == 'POST':
        user = request.user
        user.first_name = request.POST.get('firstname')
        user.last_name = request.POST.get('lastname')
        user.address = request.POST.get('address')
        request.session['amount'] = request.POST.get('amount')
        amount1 = request.POST['amount']
        request.session['article'] = id
        request.session['firstname'] = request.POST.get('firstname')
        request.session['lastname'] = request.POST.get('lastname')
        request.session['address'] = request.POST.get('address')
        
        article = Article.objects.get(id=id)
        fullPrice = article.price * float(amount1)
        request.session['fullPrice'] = fullPrice 
        context = {'fullPrice': fullPrice}
        return render(request, 'merchshop/checkout.html', context)
    else:
        return render(request, 'base/base.html')
    

    
def thankYou(request, id):
    if request.method == 'POST':
        user = get_object_or_404(CustomUser, id=id)
        if(request.POST.get('cvc') == '000'):
            firstname = request.session['firstname']
            lastname = request.session['lastname']
            address = request.session['address']
            amount = request.session['amount']
            fullPrice = request.session['fullPrice']
            user.first_name = firstname
            user.last_name = lastname
            user.address = address
            user.save()
            context = {
                'fullPrice': fullPrice,
                'firstname': firstname,
                'lastname': lastname,
                'address': address,
                'amount': amount
                }
            return render(request, 'merchshop/thankYou.html', context) 
        else:
            error_message = "Wrong CVC"
            return render(request, 'merchshop/merch.html', {'error_message': error_message})
    else:
        return render(request, 'base/home.html')

ArcadeBar/merchshop/templates/merchshop/cart.html
{% extends 'base/base.html' %}


{% block content %}

{% if error_message %}
<h1>{{ error_message }}</h1>
<h4>{{ article.title }}</h4>
<p>{{ article.price }}</p>
{% endif %}


<img src="{{ article.image }}" alt="{{ article.title }}" style="width: 260px; height: 200px;">
<p>{{ article.description }}</p>

<form action="{% url 'merchshop:checkout' article.id %}" method="POST">
    {% csrf_token %}
    <br>
    <label for="firstname">First name
        <input type="text" name="firstname">
    </label>
    <br>
    <label for="lastname">Last name
        <input type="text" name="lastname">
    </label>
    <br>
    <label for="address">Address
        <input type="text" name="address">
    </label>
    <br>
    <label for="amount">Choose your quantity
    <select name="amount" id=""> 
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="5">5</option>
        <option value="6">6</option>
        <option value="7">7</option>
        <option value="8">8</option>
        <option value="9">9</option>
        <option value="10">10</option> 
    </select>
    </label>
    <br>
    <button type="submit" class="btn btn-primary">Checkout</button>

</form>

{% endblock %}

ArcadeBar/merchshop/templates/merchshop/checkout.html
{% extends 'base/base.html' %}


{% block content %}
<h1>FULL PRICE</h1>
<h2>{{ fullPrice }}€</h2>

<p>Enter your credit card details</p>
<form action="{% url 'merchshop:thankYou' user.id %}" method="POST">
    {% csrf_token %}
    <label for="ccn">Credit Card Number:
    <input name="ccn" type="tel" inputmode="numeric" pattern="[0-9\s]{13,19}" 
         autocomplete="cc-number" maxlength="19" 
         placeholder="xxxx xxxx xxxx xxxx" required>
    </label>
    <label for="expiration_date">Expiration Date:</label>
        <input type="date" name="expiration_date">
    <label for="cvc">CVC: 
        <input name="cvc" type="text">
    </label>
    <button type="submit" class="btn btn-primary">Procceed</button>
</form>



{% endblock %}

ArcadeBar/merchshop/templates/merchshop/merch.html
<link rel="stylesheet" href="../../../base/static/base/home.css">
{% extends 'base/base.html' %}


{% block content %}

{% for article in articles %}
<form action="{% url 'merchshop:cart' article.id %}" method="POST">
    {% csrf_token %}
    <h4>{{ article.title }}</h4>
    <p>{{ article.price }}</p>
    <img src="{{ article.image }}" alt="{{ article.title }}" style="width: 260px; height: 200px;">
    <p>{{ article.description }}</p>
    {% if request.user.is_authenticated %}
    <button type="submit" class="btn btn-primary">Add to cart</button>
    {% else %}
    <a href="{% url 'accounts:login' %}" class="btn btn-primary">Login</a>
    {% endif %}
</form>
{% endfor %}


{% endblock %}

ArcadeBar/merchshop/templates/merchshop/thankYou.html
{% extends 'base/base.html' %}


{% block content %}

<h2>Thank you for your service!</h2>
<p>Here are all the informations about your order.</p>
<h3>Full price: {{ fullPrice }}</h3>
<h3>Amount: {{ amount }}</h3>
<h3>First name: {{ firstname }}</h3>
<h3>Last name: {{ lastname }}</h3>
<h3>Address: {{ address }}</h3>



{% endblock %}